/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Narudzbina;
import domen.Proizvod;
import domen.StavkaNarudzbine;
import javax.swing.JOptionPane;

/**
 *
 * @author aleks
 */
public class DodajStavkuNarudzbine extends javax.swing.JFrame {

    Proizvod proizvod;
    NovaNarudzbina forma;

    /**
     * Creates new form DodajStavkuNarudzbine
     */
    public DodajStavkuNarudzbine(NovaNarudzbina nn) {
        initComponents();
        setLocationRelativeTo(null);
        forma = nn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        txtProizvod = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        txtIznos = new javax.swing.JTextField();
        btnOdustani = new javax.swing.JButton();
        btnIzracunaj = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnIzaberi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dodaj stavku");

        jLabel1.setText("Kolicina:");

        jLabel2.setText("Proizvod:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Iznos:");

        txtProizvod.setEditable(false);

        txtCena.setEditable(false);
        txtCena.setName(""); // NOI18N

        txtIznos.setEditable(false);

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnIzracunaj.setText("Izracunaj");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzaberi.setText("Izaberi proizvod");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOdustani)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzracunaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(btnIzaberi)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnIzaberi))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOdustani)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIzracunaj)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        IzaberiProizvod ip = new IzaberiProizvod(this, true);
        ip.setVisible(true);
    }//GEN-LAST:event_btnIzaberiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (txtKolicina.getText().isEmpty() || txtKolicina.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Polje kolicina je obavezno!");
            return;
        }

        if (txtProizvod.getText().isEmpty() || txtProizvod.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Proizvod mora biti izabran!");
            return;
        }

        int kolicina = Integer.parseInt(txtKolicina.getText());

        if (kolicina <= 0) {
            JOptionPane.showMessageDialog(this, "Kolicina ne sme biti 0 ili manja od 0!");
            return;
        }

        int cena = Integer.parseInt(txtCena.getText());
        int iznos = Integer.parseInt(txtIznos.getText());
        Proizvod p = proizvod;
        System.out.println(p.getNaziv());

        StavkaNarudzbine sn = new StavkaNarudzbine(-1, kolicina, p, new Narudzbina(), cena, iznos);
        forma.dodajStavku(sn);
        JOptionPane.showMessageDialog(this, "Uspesno dodavanje!");
        this.dispose();
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed
        txtCena.setText(String.valueOf(proizvod.getCena()));
        int cena = Integer.parseInt(txtCena.getText());
        int kolicina = Integer.parseInt(txtKolicina.getText());
        int iznos = cena * kolicina;
        txtIznos.setText(String.valueOf(iznos));
    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtProizvod;
    // End of variables declaration//GEN-END:variables

    void izaberiProizvod(Proizvod p) {
        txtProizvod.setText(p.getNaziv());
        proizvod = p;
        txtCena.setText(String.valueOf(p.getCena()));
        int cena = Integer.parseInt(txtCena.getText());
        int kolicina = Integer.parseInt(txtKolicina.getText());
        int iznos = cena * kolicina;
        txtIznos.setText(String.valueOf(iznos));
    }
}
