/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Prodavac;
import javax.swing.JFrame;
import kontroler.Kontroler;

public class KlijentskaForma extends javax.swing.JFrame {

    Prodavac p;

    /**
     * Creates new form Forma1
     */
    public KlijentskaForma(Prodavac p) {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.p = Kontroler.getInstance().getCurrentProdavac();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuProizvod = new javax.swing.JMenu();
        menuSviProizvodi = new javax.swing.JMenuItem();
        menuNoviProizvod = new javax.swing.JMenuItem();
        menuKlijent = new javax.swing.JMenu();
        menuSviKlijenti = new javax.swing.JMenuItem();
        menuNoviKlijent = new javax.swing.JMenuItem();
        menuNarudzbina = new javax.swing.JMenu();
        menuSveNarudzbine = new javax.swing.JMenuItem();
        menuNovaNarudzbina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klijentska forma");

        menuProizvod.setText("Proizvodi");

        menuSviProizvodi.setText("Svi proizvodi");
        menuSviProizvodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSviProizvodiActionPerformed(evt);
            }
        });
        menuProizvod.add(menuSviProizvodi);

        menuNoviProizvod.setText("Novi proizvod");
        menuNoviProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviProizvodActionPerformed(evt);
            }
        });
        menuProizvod.add(menuNoviProizvod);

        jMenuBar1.add(menuProizvod);

        menuKlijent.setText("Klijenti");

        menuSviKlijenti.setText("Svi klijenti");
        menuSviKlijenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSviKlijentiActionPerformed(evt);
            }
        });
        menuKlijent.add(menuSviKlijenti);

        menuNoviKlijent.setText("Novi klijent");
        menuNoviKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoviKlijentActionPerformed(evt);
            }
        });
        menuKlijent.add(menuNoviKlijent);

        jMenuBar1.add(menuKlijent);

        menuNarudzbina.setText("Narudzbine");

        menuSveNarudzbine.setText("Sve narudzbine");
        menuSveNarudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSveNarudzbineActionPerformed(evt);
            }
        });
        menuNarudzbina.add(menuSveNarudzbine);

        menuNovaNarudzbina.setText("Nova narudzbina");
        menuNovaNarudzbina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaNarudzbinaActionPerformed(evt);
            }
        });
        menuNarudzbina.add(menuNovaNarudzbina);

        jMenuBar1.add(menuNarudzbina);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSviProizvodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSviProizvodiActionPerformed
        ProizvodiForma pf = new ProizvodiForma();
        pf.setVisible(true);
    }//GEN-LAST:event_menuSviProizvodiActionPerformed

    private void menuNoviProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviProizvodActionPerformed
        DodajProizvod dp = new DodajProizvod(this, true);
        dp.setVisible(true);
    }//GEN-LAST:event_menuNoviProizvodActionPerformed

    private void menuSviKlijentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSviKlijentiActionPerformed
        KlijentiForma kf = new KlijentiForma();
        kf.setVisible(true);
    }//GEN-LAST:event_menuSviKlijentiActionPerformed

    private void menuNoviKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoviKlijentActionPerformed
        DodajKlijenta dk = new DodajKlijenta(this, true);
        dk.setVisible(true);
    }//GEN-LAST:event_menuNoviKlijentActionPerformed

    private void menuSveNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSveNarudzbineActionPerformed
        NarudzbineForma nf = new NarudzbineForma();
        nf.setVisible(true);
    }//GEN-LAST:event_menuSveNarudzbineActionPerformed

    private void menuNovaNarudzbinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaNarudzbinaActionPerformed
        NovaNarudzbina nn = new NovaNarudzbina();
        nn.setVisible(true);
    }//GEN-LAST:event_menuNovaNarudzbinaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuKlijent;
    private javax.swing.JMenu menuNarudzbina;
    private javax.swing.JMenuItem menuNovaNarudzbina;
    private javax.swing.JMenuItem menuNoviKlijent;
    private javax.swing.JMenuItem menuNoviProizvod;
    private javax.swing.JMenu menuProizvod;
    private javax.swing.JMenuItem menuSveNarudzbine;
    private javax.swing.JMenuItem menuSviKlijenti;
    private javax.swing.JMenuItem menuSviProizvodi;
    // End of variables declaration//GEN-END:variables
}
