/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import domen.Prodavac;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import komunikacija.Operacije;
import komunikacija.Zahtev;
import komunikacija.Odgovor;
import komunikacija.TipOdgovora;
import kontroler.Kontroler;

/**
 *
 * @author aleks
 */
public class LoginForma extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    //private Kontroler controller;
    public LoginForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijava prodavca");

        lblUsername.setText("Username:");

        txtUsername.setText("Aleksandra");

        lblPassword.setText("Password:");

        txtPassword.setText("aleks123");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(txtUsername)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            validateForm();
            String username = txtUsername.getText().trim();
            String password = String.valueOf(txtPassword.getPassword());
            Prodavac p = new Prodavac(0, username, "", password);
            Zahtev request = new Zahtev(Operacije.LOGIN, p);
            Odgovor response = Komunikacija.getInstance().login(request);

            if (response.getResponseType().equals(TipOdgovora.SUCCESS)) {
                Prodavac prod = (Prodavac) response.getResult();
                JOptionPane.showMessageDialog(this, "Zdravo, " + prod.getIme());

                new KlijentskaForma(prod).setVisible(true);
                Kontroler.getInstance().setCurrentProdavac(prod);

                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Greska prilikom prijavljivanja!");
            }

//            Prodavac p = Kontroler.getInstance().login(txtUsername.getText().trim(), String.valueOf(txtPassword.getPassword()));
//            JOptionPane.showMessageDialog(this, "Zdravo, " + p.getIme());
//            this.dispose();
//            Kontroler.getInstance().setCurrentProdavac(p);
//            new KlijentskaForma(p).setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void validateForm() throws Exception {
        String porukaOGreskama = "";
        if (txtUsername.getText().isEmpty()) {
            porukaOGreskama += "Korisnicko ime ne sme biti prazno!\n";
        }
        if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
            porukaOGreskama += "Lozinka ne sme ostati prazna!\n";
        }
        if (!porukaOGreskama.isEmpty()) {
            throw new Exception(porukaOGreskama);
        }
    }
}
