/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.JTableHeader;
import kontroler.Kontroler;
import modeli.ModelTabeleServer;
import niti.ObradaKlijentskihZahteva;
import niti.ServerNit;

/**
 *
 * @author aleks
 */
public class ServerskaForma extends javax.swing.JFrame {

    private ServerNit sn;
    List<ObradaKlijentskihZahteva> prodavci;

    /**
     * Creates new form FrmMain
     */
    public ServerskaForma() {
        initComponents();
        btnZaustavi.setEnabled(false);
        setLocationRelativeTo(null);
        prepareForm();
        Kontroler.getInstance().setForma(this);

        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        lblServer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUlogovani = new javax.swing.JTable();
        btnKonfiguracija = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serverska forma");

        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        lblServer.setText("Serverska forma");

        tblUlogovani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUlogovani);

        btnKonfiguracija.setText("Konfiguracija");
        btnKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfiguracijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKonfiguracija)
                            .addComponent(lblServer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPokreni)
                                .addGap(206, 206, 206)
                                .addComponent(btnZaustavi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addGap(48, 48, 48)
                .addComponent(lblServer)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnKonfiguracija)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        if (sn == null || !sn.isAlive()) {
            try {
                sn = new ServerNit();
                sn.start();

                btnPokreni.setEnabled(false);
                btnZaustavi.setEnabled(true);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        lblServer.setText("Server je pokrenut!");
        lblServer.setForeground(Color.green);
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        if (sn.getServerSocket() != null && sn.getServerSocket().isBound()) {
            try {
                sn.getServerSocket().close();
                btnPokreni.setEnabled(true);
                btnZaustavi.setEnabled(false);
            } catch (IOException ex) {
                ex.printStackTrace();
            }

        }
        lblServer.setText("Server je zaustavljen!");
        lblServer.setForeground(Color.red);
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void btnKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfiguracijaActionPerformed
        KonfiguracijaForma kf = new KonfiguracijaForma(this, true);
        kf.setVisible(true);
    }//GEN-LAST:event_btnKonfiguracijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfiguracija;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblServer;
    private javax.swing.JTable tblUlogovani;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        popuniTabelu(new ArrayList<>());
    }

    private void popuniTabelu(ArrayList<OpstiDomenskiObjekat> listaProd) {
        ModelTabeleServer mtk = new ModelTabeleServer(listaProd);
        tblUlogovani.setModel(mtk);
        tblUlogovani.getColumn("Prodavac ID").setMinWidth(100);
        tblUlogovani.getColumn("Ime").setMinWidth(200);
        tblUlogovani.getColumn("Telefon").setMinWidth(100);
        tblUlogovani.getColumn("Datum prijave").setMinWidth(300);

        JTableHeader header = tblUlogovani.getTableHeader();
        header.setPreferredSize(new Dimension(100, 35));

    }

    public ModelTabeleServer vratiTabeluKorisnika() {
        return (ModelTabeleServer) tblUlogovani.getModel();
    }

}
